# Generated by Django 5.2.8 on 2025-11-26 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("stage_1", "Stage 1 - Personal Information"),
                            ("stage_2", "Stage 2 - Previous Education"),
                            ("stage_3", "Stage 3 - Course Selection"),
                            ("stage_4", "Stage 4 - Course Details Review"),
                            ("stage_5", "Stage 5 - Payment"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="stage_1",
                        max_length=20,
                    ),
                ),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("eligible", "Eligible"),
                            ("ineligible", "Ineligible"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("university_email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Admission Application",
                "verbose_name_plural": "Admission Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=20, unique=True)),
                (
                    "min_fsc_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "min_fsc_percentage",
                    models.DecimalField(decimal_places=2, default=60, max_digits=5),
                ),
                (
                    "min_matric_percentage",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                (
                    "min_aggregate_score",
                    models.DecimalField(decimal_places=2, default=70, max_digits=5),
                ),
            ],
            options={
                "verbose_name": "Admission Criteria",
            },
        ),
        migrations.CreateModel(
            name="CourseSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("BSCS", "BS Computer Science"),
                            ("BSDS", "BS Data Science"),
                            ("BSAI", "BS Artificial Intelligence"),
                            ("BSCYBERSEC", "BS Cyber Security"),
                            ("BSSE", "BS Software Engineering"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "intake",
                    models.CharField(
                        choices=[("fall", "Fall"), ("spring", "Spring")], max_length=10
                    ),
                ),
                (
                    "eligibility_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("meets_criteria", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_selection",
                        to="admission.admissionapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Selection",
            },
        ),
        migrations.CreateModel(
            name="PaymentInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "first_semester_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "student_card_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "transport_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online Payment"),
                            ("cheque", "Cheque"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("psid", models.CharField(blank=True, max_length=50, unique=True)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_info",
                        to="admission.admissionapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Information",
            },
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("father_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("cnic", models.CharField(max_length=20, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_info",
                        to="admission.admissionapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Information",
            },
        ),
        migrations.CreateModel(
            name="PreviousEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fsc_board", models.CharField(blank=True, max_length=100, null=True)),
                ("fsc_year", models.IntegerField(blank=True, null=True)),
                (
                    "fsc_marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1100),
                        ],
                    ),
                ),
                (
                    "fsc_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "matric_board",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("matric_year", models.IntegerField(blank=True, null=True)),
                (
                    "matric_marks",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1050),
                        ],
                    ),
                ),
                (
                    "matric_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("additional_qualifications", models.TextField(blank=True)),
                (
                    "fsc_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="admission/documents/"
                    ),
                ),
                (
                    "matric_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="admission/documents/"
                    ),
                ),
                (
                    "cnic_scan",
                    models.FileField(
                        blank=True, null=True, upload_to="admission/documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_education",
                        to="admission.admissionapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Previous Education",
            },
        ),
        migrations.CreateModel(
            name="ProgramDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=20)),
                ("program_duration_semesters", models.IntegerField(default=8)),
                ("total_credits", models.IntegerField(default=120)),
                (
                    "admission_fee",
                    models.DecimalField(decimal_places=2, default=15000, max_digits=10),
                ),
                (
                    "semester_fee",
                    models.DecimalField(decimal_places=2, default=75000, max_digits=10),
                ),
                (
                    "student_card_fee",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "transport_fee",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=10),
                ),
                ("semester_roadmap", models.TextField(blank=True)),
                ("agree_terms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_details",
                        to="admission.admissionapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Details",
            },
        ),
        migrations.CreateModel(
            name="SemesterRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=20)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=20)),
                ("course_title", models.CharField(max_length=200)),
                ("credits", models.IntegerField()),
            ],
            options={
                "verbose_name": "Semester Roadmap",
                "unique_together": {("program", "semester", "course_code")},
            },
        ),
    ]
