# Generated by Django 5.2.8 on 2025-11-26 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Grade Scale",
                "verbose_name_plural": "Grade Scales",
            },
        ),
        migrations.CreateModel(
            name="AssessmentComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("midterm", "Midterm"),
                            ("final", "Final Exam"),
                            ("practical", "Practical"),
                            ("project", "Project"),
                            ("participation", "Class Participation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "total_marks",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "weightage",
                    models.IntegerField(
                        help_text="Percentage weight in final grade",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_components",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.teacherprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Component",
                "verbose_name_plural": "Assessment Components",
                "ordering": ["due_date"],
                "unique_together": {("course", "component_type", "name")},
            },
        ),
        migrations.CreateModel(
            name="GPAPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_cgpa", models.DecimalField(decimal_places=2, max_digits=3)),
                ("predicted_cgpa", models.DecimalField(decimal_places=2, max_digits=3)),
                (
                    "prediction_based_on",
                    models.IntegerField(
                        help_text="Number of courses used for prediction"
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence percentage (0-100)",
                        max_digits=3,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gpa_prediction",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "GPA Prediction",
                "verbose_name_plural": "GPA Predictions",
            },
        ),
        migrations.CreateModel(
            name="GradeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("grade", models.CharField(max_length=2)),
                (
                    "gpa_points",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("graded_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="courses.course",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.teacherprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Entry",
                "verbose_name_plural": "Grade Entries",
                "ordering": ["-graded_date"],
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="GradeAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appeal_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_comments", models.TextField(blank=True)),
                (
                    "new_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("appealed_date", models.DateTimeField(auto_now_add=True)),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_appeals_reviewed",
                        to="accounts.teacherprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_appeals",
                        to="accounts.studentprofile",
                    ),
                ),
                (
                    "grade_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appeals",
                        to="grades.gradeentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Appeal",
                "verbose_name_plural": "Grade Appeals",
                "ordering": ["-appealed_date"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("submission_file", models.FileField(upload_to="submissions/")),
                ("submission_date", models.DateTimeField()),
                ("is_late", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted"),
                            ("late_submitted", "Late Submitted"),
                            ("graded", "Graded"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("teacher_comments", models.TextField(blank=True)),
                ("graded_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="grades.assessmentcomponent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_submissions",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Submission",
                "verbose_name_plural": "Assessment Submissions",
                "ordering": ["-submission_date"],
                "unique_together": {("student", "assessment")},
            },
        ),
        migrations.CreateModel(
            name="SemesterGPA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.IntegerField()),
                ("total_credits", models.IntegerField(default=0)),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("academic_standing", models.CharField(blank=True, max_length=50)),
                ("calculated_date", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_gpas",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semester GPA",
                "verbose_name_plural": "Semester GPAs",
                "ordering": ["-semester"],
                "unique_together": {("student", "semester")},
            },
        ),
    ]
